all: 
	pdflatex umanual.tex
	pdflatex umanual.tex
	pdflatex umanual.tex

umanual.pdf: ummanual.tex
	pdflatex umanual.tex

clean:
	rm -rf *.log *.aux *.dvi *.toc

remove_pdf:
	rm -rf *.pdf

remove_tilde:
	rm -rf *~
