bin:
	(cd src; make)

demo:
	(cd example; make)

test:
	(cd testing; make)

clean:
	rm -f matexpr
	(cd src; make clean)
	(cd example; make clean)

realclean: clean
	(cd src; make realclean)
	(cd doc; make realclean)
